### ISSUE TITLE
random malloc error

### ISSUE THREAD

**Issue by YangKeao** [YangKeao/rsperftools#4]
```
malloc(): unsorted double linked list corrupted
malloc(): mismatching next->prev_size (unsorted)
segmentation fault
...
```

These errors occurs randomly. Here is one of the backtrace.

```
#0  0x00007fa41b9a4f3b in raise () from /lib64/libc.so.6
#1  0x00007fa41b98e535 in abort () from /lib64/libc.so.6
#2  0x00007fa41b9eadd7 in ?? () from /lib64/libc.so.6
#3  0x00007fa41b9f2c38 in ?? () from /lib64/libc.so.6
#4  0x00007fa41b9f5d0c in ?? () from /lib64/libc.so.6
#5  0x00007fa41b9f7453 in malloc () from /lib64/libc.so.6
#6  0x00005641846f5c2c in <alloc::vec::Vec<T> as core::clone::Clone>::clone ()
#7  0x00005641846f3a3d in <core::iter::adapters::Cloned<I> as core::iter::traits::iterator::Iterator>::fold ()
#8  0x00005641846f5bae in alloc::vec::Vec<T>::extend_from_slice ()
#9  0x00005641846f46f8 in <hashbrown::raw::RawTable<T> as core::clone::Clone>::clone ()
#10 0x00005641846f2d6d in rsperftools::profiler::Profiler::report ()
#11 0x00005641846f1993 in two_way::main ()
#12 0x00005641846f1ec3 in std::rt::lang_start::{{closure}} ()
#13 0x0000564184711fb3 in std::rt::lang_start_internal::{{closure}} () at src/libstd/rt.rs:49
#14 std::panicking::try::do_call () at src/libstd/panicking.rs:296
#15 0x00005641847140fa in __rust_maybe_catch_panic () at src/libpanic_unwind/lib.rs:82
#16 0x0000564184712abd in std::panicking::try () at src/libstd/panicking.rs:275
#17 std::panic::catch_unwind () at src/libstd/panic.rs:394
#18 std::rt::lang_start_internal () at src/libstd/rt.rs:48
#19 0x00005641846f1c42 in main ()
```

**Comment by YangKeao** [comment]
As for [signal-safety](http://man7.org/linux/man-pages/man7/signal-safety.7.html), I shouldn't call malloc in signal handler !

**Comment by YangKeao** [comment]
This issue has been fixed. The only signal-unsafe part is calling backtrace while rust handling panic.
